import {
  Headline,
  PageHeader,
  PageWrapper,
  Paragraph,
} from '@app/shared/ui/components';
import { FONT_WEIGHT } from '@app/shared/ui/theme';
import {
  Box,
  OrderedList,
  useColorMode,
  ListItem,
  UnorderedList,
  Flex,
} from '@chakra-ui/react';
import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';

import { StyledTerms } from './StyledTerms';

export const Terms = () => {
  const { t } = useTranslation();
  const { colorMode } = useColorMode();
  const navigate = useNavigate();

  return (
    <StyledTerms $colorMode={colorMode}>
      <PageWrapper>
        <PageHeader
          btnLabel={t('system.back')}
          onBtnClick={() => navigate(-1)}
        />
        <Box mt={8}>
          <Headline
            size={3}
            fontWeight={FONT_WEIGHT.SEMI_BOLD}
            textAlign={'center'}
          >
            {t('system.termsOfService')}
          </Headline>
        </Box>
        <Box className={'terms-updated'} mt={8} mb={10}>
          <Paragraph
            size={2}
            fontWeight={FONT_WEIGHT.REGULAR}
            textAlign={'center'}
          >
            Last updated July 2023
          </Paragraph>
        </Box>
        <Paragraph size={2} fontWeight={FONT_WEIGHT.REGULAR}>
          Between <br />
          All4Labels Group GmbH <br />
          Möllner Landstraße 15 <br />
          22969 Witzhave <br />
          Germany <br />
          <br />
          (“A4L") <br />
          And <br />
          The Registered User Legal Address & Contact <br />
          ("Customer") <br />
          (collectively "the Parties") <br />
          <br />
          <OrderedList>
            <ListItem>
              <b>Subject Matter</b>
              <OrderedList css={{ listStyle: 'lower-alpha' }}>
                <ListItem>
                  <b>A4L provides the following services:</b>
                  <UnorderedList>
                    <ListItem>
                      A4L generates QR codes, so-called short links or short
                      URLs ("Short Links"), for the Customer.
                    </ListItem>
                    <ListItem>
                      A4L shall provide the Customer with regular evaluations of
                      the API calls of the created Short Links ("Analytics").
                    </ListItem>
                    <ListItem>
                      A4L shall provide the Customer with a forwarding (linking)
                      of the end user to a website (“Target Page”) designated by
                      the Customer upon use of the Short Links ("Linking").
                    </ListItem>
                  </UnorderedList>
                </ListItem>
                <li>
                  The use of the Short Links generated by A4L including the
                  forwarding to the Target Page and the Analytics require the
                  use of a software solution from A4L (the "A4L Software"). The
                  A4L Software is a so-called SaaS solution and is used
                  exclusively cloud-based or web-based.
                </li>
              </OrderedList>
            </ListItem>
            <ListItem>
              <b>Rights of Use</b>
              <OrderedList css={{ listStyle: 'lower-alpha' }}>
                <ListItem>
                  A4L grants the Customer a limited, non-exclusive,
                  non-transferable, non-sublicensable, and non-modifiable right
                  for the term of this Agreement to use the A4L Software for the
                  Customer's business operations under the terms of this
                  Agreement to the extent agreed herein. Use for the business
                  operations of third parties is not permitted.
                </ListItem>
                <ListItem>
                  Without prejudice to the rights of use granted under this
                  Agreement, A4L retains all rights in the A4L Software and all
                  intellectual property rights associated with the digital
                  solutions of A4L.
                </ListItem>
                <ListItem>
                  The Customer is aware that the licensed A4L Software is linked
                  to open-source components which are described in Annex A. A4L
                  uses open-source components under the respective open-source
                  licence.
                </ListItem>
                <ListItem>
                  With regard to the open-source components contained in the A4L
                  Software, A4L grants the Customer a non-exclusive right of use
                  with the corresponding restrictions. A4L and the Customer
                  shall in this respect observe all obligations arising from the
                  open-source licence conditions brought to the attention of the
                  Customer.
                </ListItem>
              </OrderedList>
            </ListItem>
            <ListItem>
              <b>Use of the A4L Software by the Customer</b>
              <br />
              The Customer undertakes to take appropriate security precautions
              to ensure that access to the A4L Software is not used by
              unauthorised persons. These security precautions include, in
              particular but not limited to, the use of secure passwords, access
              restrictions and employee checks.
            </ListItem>
            <ListItem>
              <b>Linking Data and Content via the A4L Software</b>
              <OrderedList css={{ listStyle: 'lower-alpha' }}>
                <ListItem>
                  The Customer has the option to make a website or webpage
                  created by the Customer, including data, text, images and
                  other information ("Customer Content"), publicly accessible
                  via the Short Links and the A4L Software by means of an API
                  call.
                </ListItem>
                <ListItem>
                  The Customer shall only link to Customer Content or make
                  Customer Content publicly available via the A4L Software
                  provided that the respective Customer Content
                  <UnorderedList>
                    <ListItem>
                      does not infringe third-party rights; and
                    </ListItem>
                    <ListItem>
                      is not unlawful, racist, hostile, violent, discriminatory,
                      harmful, harassing, defamatory, or otherwise
                      objectionable; and
                    </ListItem>
                    <ListItem>
                      does not contain software viruses or other computer code,
                      files or programs designed to interrupt, destroy or limit
                      the functionality of any computer software or hardware or
                      telecommunications equipment.
                    </ListItem>
                  </UnorderedList>
                </ListItem>
                <ListItem>
                  The Customer agrees that A4L may process the Customer Content
                  linked by the Customer and other data for the purposes of this
                  Agreement, in particular to enable the end user or third
                  parties to be forwarded to such linked content. A4L will not
                  store, copy, analyze, monitor or otherwise use that data
                  except for the purposes set forth in the License Agreement.
                </ListItem>
                <ListItem>
                  The Customer will comply fully with all applicable laws,
                  regulations, and government orders in People’s Republic of
                  China relating to personally identifiable information (“PII”)
                  and data privacy with respect to any such data that A4L
                  receives or has access to under the License Agreement or in
                  connection with the performance of any services for the
                  Customer. A4L will otherwise protect PII and will not use,
                  disclose, or transfer across borders such PII except as
                  necessary to perform under the License Agreement or as
                  authorized by the data subject or in accordance with
                  applicable law.
                </ListItem>
                <ListItem>
                  A4L shall be entitled to prevent the forwarding to Customer
                  Content linked by the Customer if A4L has reasonable grounds
                  to believe that the Customer Content does not comply with the
                  provisions of this Agreement and/or infringes applicable law
                  or third-party rights.
                </ListItem>
                <ListItem>
                  Insofar as the Customer permits or enables end users or third
                  parties to use the A4L Software and, in particular, enables
                  them to link to content, to upload, transfer or otherwise make
                  available data or content via the A4L Software, the Customer
                  undertakes to ensure that these end users or other third
                  parties are obliged to comply with the obligations set out in
                  this Agreement and shall indemnify A4L against all claims
                  raised against A4L based on a possible breach of these
                  obligations.
                </ListItem>
              </OrderedList>
            </ListItem>
            <ListItem>
              <b>Availability</b>
              <OrderedList css={{ listStyle: 'lower-alpha' }}>
                <ListItem>
                  A4L warrants an availability of the A4L Software of 99%.
                </ListItem>
                <ListItem>
                  A4L is not responsible for an unavailability of the A4L
                  Software ("Downtime") in case this Downtime is
                </ListItem>
                <UnorderedList>
                  <ListItem>
                    due to technical or other problems for which A4L is not
                    responsible (force majeure, fault of third parties, errors
                    in the IT systems of the Customer or the third-party service
                    providers commissioned by the Customer, etc.);
                  </ListItem>
                  <ListItem>
                    based on a breach of the Customer's duty to cooperate, in
                    particular on a late or incomplete transmission of an error
                    message; or
                  </ListItem>
                  <ListItem>
                    due to normal maintenance work of up to five hours a month.
                  </ListItem>
                </UnorderedList>
              </OrderedList>
            </ListItem>
            <ListItem>
              <b>Operation and changes to the software</b> <br />
              A4L shall be entitled to introduce updates, new versions or
              upgrades of the A4L Software ("Update") from time to time in order
              to adapt the A4L Software to new technical or commercial
              requirements, to implement new functions or to make changes to
              existing functions in order to improve the A4L Software.
            </ListItem>
            <ListItem>
              <b>Remuneration and terms of payment</b> <br />
              The remuneration for the use of the A4L Software is agreed
              together with the offer for the labels and shall be invoiced with
              the supply of the labels.
            </ListItem>
            <ListItem>
              <b>Warranty</b>
              <OrderedList css={{ listStyle: 'lower-alpha' }}>
                <ListItem>
                  A4L warrants that the Customer may use the A4L Software to the
                  extent agreed under this Agreement.
                </ListItem>
                <ListItem>
                  In case the A4L is not available to the extent as agreed on in
                  Clause 5, A4L will refund the remuneration paid for the use of
                  the A4L Software upon written notice of the Customer for the
                  time of unavailability.
                </ListItem>
                <ListItem>
                  A4L does not warrant that the A4L Software will meet any
                  particular operational requirements or purposes of the
                  Customer or will interoperate with other programs selected by
                  the Customer.
                </ListItem>
              </OrderedList>
            </ListItem>
            <ListItem>
              <b>Hotline and customer service</b>
              <OrderedList css={{ listStyle: 'lower-alpha' }}>
                <ListItem>
                  A4L provides the Customer with free customer service via email
                  (support@a4lcloud.com) from 8 am to 5 pm (CET) on all working
                  days in Hamburg, Germany.
                </ListItem>
                <ListItem>
                  In the event of malfunctions of the A4L Software, free support
                  is available to the Customer by email ((support@a4lcloud.com))
                  10 hours a day from 8 am to 6 pm (Berlin Time). In the event
                  of serious malfunctions that significantly impair the use of
                  the A4L Software, A4L shall grant a reaction time of 60
                  minutes within the business hours.
                </ListItem>
              </OrderedList>
            </ListItem>
            <ListItem>
              <b>Liability</b>
              <OrderedList css={{ listStyle: 'lower-alpha' }}>
                <ListItem>
                  A4L shall only be liable insofar as the damage occurred
                  <UnorderedList>
                    <ListItem>
                      was caused by an at least negligent breach of an essential
                      contractual obligation for which A4L is responsible and
                      the conduct causing the damage was suitable to jeopardise
                      the achievement of the purpose of the Agreement, or
                    </ListItem>
                    <ListItem>was caused intentionally, or</ListItem>
                    <ListItem>
                      is based on a grossly negligent breach of duty for which
                      A4L is responsible.
                    </ListItem>
                  </UnorderedList>
                </ListItem>
                <ListItem>
                  Liability is limited to the damage that A4L typically had to
                  expect at the time of conclusion of the Agreement on the basis
                  of the circumstances known at that time. This shall not apply
                  in the event of intentional or grossly negligent causation of
                  damage.
                </ListItem>
                <ListItem>
                  For damages caused by simple negligence, the liability shall
                  be limited to the amount of the order volume.
                </ListItem>
                <ListItem>
                  Liability for damage caused intentionally and damage resulting
                  from injury to life, limb or health due to a culpable breach
                  of duty for which A4L is responsible shall remain unaffected
                  by the above limitations of liability.
                </ListItem>
              </OrderedList>
            </ListItem>
            <ListItem>
              <b>Term and Termination</b>
              <OrderedList css={{ listStyle: 'lower-alpha' }}>
                <ListItem>
                  The term of the Agreement is 12 (twelve) months. It shall be
                  automatically extended by another 12 months period if the
                  Agreement is not terminated by one of the Parties no later
                  than 6 (six) weeks before the end of the 12-month term.
                </ListItem>
                <ListItem>
                  Any termination must be made by notice in writing.
                </ListItem>
                <ListItem>
                  Once the Agreement is terminated, the Customer shall no longer
                  have access to the accounts or data stored in the software
                  without the permission from A4L.
                </ListItem>
                <ListItem>
                  The Customer agrees that A4L may disclose the cooperation
                  between A4L and the Customer for marketing purposes and may
                  use the Customer's company logo in this context. The Customer
                  may revoke this consent at any time by written notice.
                </ListItem>
              </OrderedList>
            </ListItem>
            <ListItem>
              <b>Audit</b>
              <OrderedList css={{ listStyle: 'lower-alpha' }}>
                <ListItem>
                  The Customer agrees that A4L may, upon fifteen (15) days after
                  sending a written notice, audit the Customer’s Use of the A4L
                  Software and may disclose results of such audit to its
                  applicable third-party right holders. The audit shall focus on
                  the functions, application, backup or archiving records of the
                  software, if any, to ensure that the software has been
                  installed, used, saved and operated in compliance with the
                  quantity ordered in the contract, and the terms and conditions
                  of this Agreement.
                </ListItem>
                <ListItem>
                  A4L reserves the right to appoint a third party to act on
                  A4L’s behalf in the audit. The Customer agrees to cooperate
                  with A4L’s audit and provide reasonable assistance and access
                  to information including but not limited to relevant books,
                  reports, contracts, technical support documents, and order
                  reporting system. The Customer understands and agrees that A4L
                  may disclose the licensed quantity and relevant audit
                  information to third-party right holders, and such disclosure
                  shall not be deemed as a violation of confidentiality
                  obligations herein or elsewhere.
                </ListItem>
              </OrderedList>
            </ListItem>
            <ListItem>
              <b>Final provisions</b>
              <OrderedList css={{ listStyle: 'lower-alpha' }}>
                <ListItem>
                  If any provision of this Agreement is found to be invalid or
                  unenforceable by a court or administrative body of competent
                  jurisdiction, such invalidity or unenforceability shall not
                  affect the remaining provisions of this Agreement and the
                  Parties shall use their best efforts to agree in good faith
                  upon such modifications as will preserve as nearly as possible
                  the intentions expressed in this Agreement.
                </ListItem>
                <ListItem>
                  No waiver, modification or supplements to this Agreement shall
                  be effective unless it is stated in writing. This also applies
                  to the waiver of this written form requirement. The sending of
                  an e-mail shall be sufficient to fulfil the written form
                  requirement.
                </ListItem>
                <ListItem>
                  This Agreement shall be construed and governed in all respects
                  by the laws of the Federal Republic of Germany, without giving
                  effect to principles of conflicts of law. The courts of the
                  Federal Republic of Hamburg, Germany shall have exclusive
                  jurisdiction.
                </ListItem>
              </OrderedList>
            </ListItem>
          </OrderedList>
          <br />
        </Paragraph>
        <Paragraph size={2} fontWeight={FONT_WEIGHT.REGULAR}>
          <Flex flexDir="row" justifyContent="space-between" mt="4">
            <Flex flexDir="column" alignItems="center">
              <Box mb="4">Hamburg,__________________</Box>
              <Box>___________________________</Box>
              <Box>All4Labels Group GmbH</Box>
            </Flex>
            <Flex flexDir="column" alignItems="center">
              <Box mb="4">___________________________</Box>
              <Box>___________________________</Box>
              <Box>(Customer)</Box>
            </Flex>
          </Flex>
        </Paragraph>
      </PageWrapper>
    </StyledTerms>
  );
};
